version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /tests/integration/csaf-validator
    schedule:
      interval: weekly
      day: monday
      time: "09:15"
    groups:
      csaf-validator-dependencies:
        patterns:
          - "*"
